language: perl
before_install:
  - perlbrew -f install-cpanm
install: cpanm -nq --installdeps --with-recommends --with-suggests .
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - '5.8'
